# ===============================
# = Hibernate datasource
# ===============================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: root

# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    
# =============================================
# = Google Recaptcha configurations
# = https://www.google.com/recaptcha/admin#list
# =============================================
google:
  recaptcha:
    url: https://www.google.com/recaptcha/api/siteverify
    key: 6Ldzv-sUAAAAAB02M3nV7iH-9jLMgW3GGjgxVqk5
    secret: 6Ldzv-sUAAAAAFAMhCfWdDCCfqec8xN-wREHkPyT